# Generated by Django 3.1.7 on 2022-07-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_address'),
        ('tlc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='useruploadedfile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
