# Generated by Django 3.2.13 on 2022-10-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_time', models.DateTimeField()),
                ('meeting_content', models.CharField(max_length=200)),
                ('meeting_url', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('meeting_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingGuest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_guest', to='meeting.meeting')),
                ('meeting_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_guest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_guest',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
