# Generated by Django 3.2.13 on 2022-10-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20221029_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_url',
            field=models.CharField(max_length=200),
        ),
    ]
